### ISSUE TITLE
Question: Differences between this project and opendis7-java

### ISSUE THREAD

**Issue by alessiomatricardi** [open-dis/open-dis-java#154]
Hi,

I'm going to start a personal project which relies on DIS and was wondering which were the differences between this project and opendis-7-java (https://github.com/open-dis/opendis7-java).

I'm asking because, as I can see, both supports version 7, but this repository seems more maintained and it's published onto Maven Central.
At the opposite, opendis-7 has a great build-in listener mechanism.

I'm sorry if the question seems stupid, but I can't understand.
Thanks in advance :)

**Comment by leif81** [comment]
The opendis7-java project is a newer experimental implementation of dis7 using a new code generator.

This open-dis-java project here continues to be maintained in parallel because it's used in many production applications.

At some point in the future the two projects might merge back together, but it's to be decided how that would be best done.

**Comment by leif81** [comment]
The opendis7-java project is a newer experimental implementation of dis7 using a new code generator.

This open-dis-java project here continues to be maintained in parallel because it's used in many production applications.

At some point in the future the two projects might merge back together, but it's to be decided how that would be best done.

@alessiomatricardi can you describe what you meant by listener mechanism?

**Comment by alessiomatricardi** [comment]
> Great question.
> 
> The opendis7-java project is a newer experimental implementation of dis7 using a new code generator.
> 
> This open-dis-java project here continues to be maintained in parallel because it's used in many production applications.
> 
> At some point in the future the two projects might merge back together, but it's to be decided how that would be best done.

Great, thanks you for the explaination. Is there any discussion of posting it to Maven Central as beta for testing purposes?

> @alessiomatricardi can you describe what you meant by listener mechanism?
I was seeing at this https://github.com/open-dis/opendis7-java/blob/master/src/edu/nps/moves/dis7/utilities/DisThreadedNetworkInterface.java which is more refined than https://github.com/open-dis/open-dis-java/blob/master/src/main/java/edu/nps/moves/disutil/DisConnection.java.
Another thing I noted is that DisConnection utility class only supports v6 Pdu, can I make a PR to add a v7 implementation too?
