### ISSUE TITLE
Call the next release 5.0?

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-java#24]
I'm in the midst of preparing to cut the next release of open-dis to deploy to Maven Central. I'm fixing up the pom.xml, tweaking the readme a bit, and cleaning up a few misc things that I'll have in the PR. But it got me thinking...

Quite a few very large changes have happened recently, namely dropping hibernate and jaxb support which meant the `dismobile` and `dismobile7` packages were removed. Also, not to mention restructuring the repository when it was moved to github. These things feel like enough to call this release `5.0`.

@mcgredonps what do you think?

**Comment by IanMayo** [comment]
I have a private branch of the code. I will have to check if I have anything to contribute back to the main repo. But, I am away until Monday 11th.

**Comment by leif81** [comment]
@IanMayo Ok great. Waiting until you're back should be fine. 

I still need some time to figure out which PC I placed my gpg key on that I use to sign the releases for Maven Central. :fearful: 

Roughly speaking I was hoping to cut a release before the end of April, since I have some time to devote to it this month.

**Comment by mcgredonps** [comment]
Bumping to 5.0 is fine. (I think programmers are always loathe to major-rev bump
because they never want to admit something is finished. Going from 0.x to 1.x
is always a battle.)

On Apr 2, 2016, at 7:09 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


@IanMayo<https://github.com/IanMayo> Ok great. Waiting until you're back should be fine.

I still need some time to figure out which PC I placed my gpg key on that I use to sign the releases for Maven Central. [:fearful:]

Roughly speaking I was hoping to cut a release before the end of April, since I have some time to devote to it this month.

**Comment by leif81** [comment]
Don, I completely agree. These days I just tell myself it's just a number. No sooner than we release a 5.0 artifact, we'll want to do a 5.1, or 5.0.1. Which is great. The more we iron out the release process the easier it'll be.

FWIW, I'm totally on the Semantic Versioning (www.semver.com) bandwagon these days so that's where some of this motivation is coming from.

Since this "issue" was just a question I'll go ahead and close this now that we're on the same page.

**Comment by IanMayo** [comment]
@leif81  - I'm back at work now, and have checked my working sources against master.  I don't have any outstanding fixes - my changes have already been included, as PRs.

Good luck with the release :-D

**Comment by leif81** [comment]
My original timeline of 5.0 release for end of April is slipping a bit. The fact I lost my key for deploying to Sonatype (effectively Maven Central) isn't making things easier! Stay tuned.
