### ISSUE TITLE
Can't find latest release in Maven Central or Jcenter

### ISSUE THREAD

**Issue by kastork** [open-dis/open-dis-java#51]
Could you provide info on a repository where the current release can be found?

**Comment by leif81** [comment]
Hi @kastork . I haven't done a proper release lately. I really should since it's been so long! 

As an interim solution, what I've personally been using is the fabulous service called http://www.jitpack.io which lets you as a developer add any github Maven project as a dependency to your project for "free" without waiting for someone like me to publish a proper release to Maven Central, etc.

e.g. Add this to your `pom.xml`

```
<repositories>
	<repository>
	    <id>jitpack.io</id>
	    <url>https://www.jitpack.io</url>
	</repository>
</repositories>
```

And then add this to your depenencies section. Choose your own sha1.

```
<dependency>
    <groupId>com.github.open-dis</groupId>
    <artifactId>open-dis-java</artifactId>
    <version>bb549e2a783a78b0e3bf6d6f5d77592d77a99081</version> <!-- locked to a particular 5.0-SNAPSHOT with jitpack.io -->
</dependency>
```

**Comment by kastork** [comment]
I keep forgetting about jitpack.  Thanks for the reminder.
