### ISSUE TITLE
Update maven dependency

### ISSUE THREAD

**Issue by scottrbrtsn** [open-dis/open-dis-java#53]
It looks like you have .jar's for up to 4.16 but the maven dependency is only at 4.08...

**Comment by leif81** [comment]
Yep! Good eye. There were some non Maven releases that happened in there. To be honest I have a love hate relationship with Maven Central. I must be doing something wrong because it always seems to take me a lot of brain power to figure out how to publish to MC. Anyhow that's my problem.

In the mean time, I'd suggest looking at the comments in #51 for a workaround I recommend that uses the jitpack.io Maven repository which requires no effort on my part!

**Comment by scottrbrtsn** [comment]
Just thought I'd make a note.  Was able to import the latest jar manually and it seems to work fine now.

Thank you for following up with this.

**Comment by leif81** [comment]
Hi Scott, so you're aware, the 4.16 jar is about a year old now. So if you encounter any issues try using the latest code on the master branch as a Maven dependency with jitpack.

**Comment by scottrbrtsn** [comment]
I used the suggestions for  #51.
