### ISSUE TITLE
Problems decoding multiple PDUs in datagram; decoded as may as possible

### ISSUE THREAD

**Issue by scottrbrtsn** [open-dis/open-dis-java#54]
Any idea why I'm getting this in the console (infinitely) as a result of a generic exception:  "Problems decoding multiple PDUs in datagram; decoded as may as possible"

From line 428 in PduFactory.java (getPdusFromBundle)

https://github.com/open-dis/open-dis-java/blob/master/src/main/java/edu/nps/moves/disutil/PduFactory.java

The implementation I was using (was working until a few days ago, I think something got pushed from our DIS folks) 

```
public List<Pdu> getCurrentBundle() {
        List<Pdu> toReturn = new ArrayList<>();
        LOGGER.debug("getBundle");
        try {
            toReturn = getListFromBuffer();
        } // End try
        catch (Exception e) {
            LOGGER.error(e);
        }

        return toReturn;
   }

    private List<Pdu> getListFromBuffer(){
        DatagramPacket packet;
        PduFactory pduFactory = new PduFactory();
        byte buffer[] = new byte[MAX_PDU_SIZE];
        packet = new DatagramPacket(buffer, buffer.length);
        try {
            socket.receive(packet);
        }catch (Exception e){
            LOGGER.error(e);
        }
        List<Pdu> pduBundle = pduFactory.getPdusFromBundle(packet.getData());
        return  pduBundle;
    }
```

**Comment by leif81** [comment]
I'm guessing `PduFactory.createPdu` is throwing that exception. It's hard to know exactly why without your data, but could one of the Pdu's be malformed?

That error message your're seeing repeated...I think what should be happening is the `catch` in `PduFacotry.getPdusFromBundle` should be calling `break`. Otherwise the value of `pduStartPointInData ` won't change and on the next loop it will call `createPdu` with the same byte buffer. That part is an easy improvement, I'll fix that.

https://github.com/open-dis/open-dis-java/blob/master/src/main/java/edu/nps/moves/disutil/PduFactory.java#L426

**Comment by scottrbrtsn** [comment]
This was triggered by a pdu made during development, and was also structured to be a DataPdu but with pduType set to be a SetDataPdu, and was structured incorrectly.  

I copied the function and added a `break`.  This proved to fix the problem as it no longer continued in the infinite loop.

**Comment by leif81** [comment]
Ok good to hear.

Btw if you pull the latest build from jitpack it will have this fix in it now.

**Comment by mcgredonps** [comment]
The PDUFactory for receiving binary PDUs works by doing a handoff:


Hand off a received -from-the-network binary backet, extract it from the udp packet, and and the content off to PDUFactory. It works for a single PDU.


The PDUFactory peaks a few bytes into the first packet by just reading a few bytes in and decoding it. It uses that to create a new instance of a PDU.


All PDUs are subclasses of the generic PDU, which have the same fields. They've also got their own fields. Each PDU calls the top-level constructor, which has values in the same name and format. (A few PDUs have family PDUs, and the construction can also use that.)


A badly formed (or incorrectly written) constructor will return a null value.


Multiple PDUs in one packets are used outside open-dis, but we just didn't implement that for what we did.  It will be pretty easy to do. Send in directly concatenated PDUs. Have the PDU factory return a list or array of PDUs. Protecting against errors with code that might not correctly be decoding them is an issue. Maybe your app doesn't decode directed energy, or some other PDU not implemented PDU. There is a PDULength field in the header; you can use that to tell yourself about the length of PDUs, and not have to correctly decode them. and therefore when your are done reading the packet is not over read.


there's some message delay issues if you pack up a dozen ESPDUs in one packet. IE, having triggers both number of packets and time since last ESPDU sent. But there are good reasons to use it, especially in Javascript web applications.


As education people we were pretty lazy. There's some surprising practical outcomes. An architecture API by us talk would be good, what form the PDU lists are passed in, and so on. As I recall the size limit on DIS UDP collection of PDUs is 8K. I don't know what sort of API pattern commercial implementations use.



java/edu/nps/moves/disutil/PduFactory.java



________________________________
